# Application configuration
#
# This file defines all configuration values for a mangoo I/O application.
# The default values are loaded by default and overwritten by environment specific
# values if they are configured.
#
# Possible environments are test and dev.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

default:
    application:
        name       : ${application-name}
        secret     : ${application-secret}
        language   : en
    connector:
        http:
            host      : localhost
            port      : 8080
    auth:
        redirect  : /login
        cookie:
            name    : ${application-name}-authentication
            encrypt : false
            expires : 86400
    session:
      cookie:
        name       : ${application-name}-session
        expires    : 86400
        encryption : false
    smtp:
        host       : localhost
        port       : 25
        username   :
        password   :
        ssl        : false

test:
    connector:
        http:
            host      : localhost
            port      : 9090
    smtp:
        port       : 3025

dev:
    connector:
        http:
            host      : localhost
            port      : 9090
    smtp:
        port       : 3025
